# Generated by Django 4.1.2 on 2022-10-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ADMIN'), (2, 'MODERATOR'), (3, 'EDITOR'), (4, 'USER')], default=4),
        ),
    ]
